Steven Yahir García Galván

26/08/2024

## A03-PYTHON

In [5]:
import pandas as pd 

datosct = pd.read_excel("datosCT.xlsx")

In [6]:
datosct

Unnamed: 0  Ingreso  Gasto
0        Enero     1340   1880
1      Febrero     2590   3130
2        Marzo     3570   2140
3        Abril     4450   3370
4         Mayo     1330   2990
5        Junio     1610   1970
6        Julio     1500   2230
7       Agosto     2270   1240
8   Septiembre     1910   1470
9      Octubre     2120   2280
10   Noviembre     3950   1870
11   Diciembre     1380   3140

## calcula la Utilidad (Ingreso - Gasto)

In [7]:
datosct["utilidad"] = datosct["Ingreso"]- datosct["Gasto"]

In [8]:
datosct

Unnamed: 0  Ingreso  Gasto  utilidad
0        Enero     1340   1880      -540
1      Febrero     2590   3130      -540
2        Marzo     3570   2140      1430
3        Abril     4450   3370      1080
4         Mayo     1330   2990     -1660
5        Junio     1610   1970      -360
6        Julio     1500   2230      -730
7       Agosto     2270   1240      1030
8   Septiembre     1910   1470       440
9      Octubre     2120   2280      -160
10   Noviembre     3950   1870      2080
11   Diciembre     1380   3140     -1760

## encuentra el promedio de Gastos en los meses que la Utilidad fue negativa

In [13]:
suma_gastos_negativos=(1880 ,3130 , 2990, 1970, 2230, 2280, 3140)
promedio = sum(suma_gastos_negativos) / len(suma_gastos_negativos)
promedio

2517.1428571428573

## encuentra los ingresos totales del año

In [15]:
ingresos_totales=sum(datosct["Ingreso"])

In [16]:
ingresos_totales

28020

## Crea las siguientes estructuras usando numpy

In [17]:
import numpy as np 

a = np.array([[1,2],
              [3,4]])

b = np.array([[2],
             [4]])

In [18]:
a

array([[1, 2],
       [3, 4]])

In [19]:
b

array([[2],
       [4]])

## Encuentra el resultado de ab

In [20]:
ab = np.dot(a,b)
ab

array([[10],
       [22]])